name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GO111MODULE: on

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ "1.18.x" ]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Install dependencies
      run: go get -t -v ./...

    - name: Gofmt
      run: diff -u <(echo -n) <(gofmt -d .)

    - name: Test
      run: go test -v -race ./...

    - name: Vet
      run: go vet ./...
